* Getting data from airtable
- [ ] The "old" copy of the data should be saved and accessible before retrieving the new copy.
- [ ] Need to set up a system where we store backup files of airtable data each time we sync.
  - For each new sync we look at the last version.
- [ ] Compare the new copy with the old and construct lists of:
  - [ ] items to add
  - [ ] items to remove
  - [ ] items to update
- [ ] Use all three lists to sync the data with the other services.
- We could conceivably use our stored backups to restore the airtable data if we really mess things up.
- For the airtable data we should use personal email as the primary identifier
  - Even though this is field can be updated, a DELETE followed by a POST to the other services is as good as a PUT
* Google workspace
- [ ] Need to figure out why the `/groups` endpoint is returning a 503
* Action Network
- We can only access individual records via Action Network's uuid primary key (not email or other identifier).
  - This means we need to retrieve *all* Action Network data before we can determine how to sync it.
- [X] First step is to send a series of http requests (25 item limit per request) to get all records.
- [ ] Once we have all records we can compare the data with airtable and sync.
